coordinate_t = [vector_lonTangent; -1 * vector_latTangent; vector_Sat];
[pitch_t, azimuth_t] = F_coordinateTransform(coordinate_t, -1 * vector_AreaSat);
azimuth_t(pitch_t < 0) = azimuth_t(pitch_t < 0) + pi;
pitch_t(pitch_t < 0) = - 1 * pitch_t(pitch_t < 0);
pitch_t = pi - pitch_t;
pitch_t = pitch_t * 180 / pi;
x = pitch_t .* cos (azimuth_t);
y = pitch_t .* sin (azimuth_t);

figure(1);
powerCtrl = -108;
x_plot = x(powerOfAreas >= powerCtrl);
y_plot = y(powerOfAreas >= powerCtrl);
plot(x_plot, y_plot, '*');
axis([-80,80,-80,80]);
ylabel('经度方向，正向指向西');
xlabel('纬度方向，正向指向北');
title_t = ['thriftAngle:', sprintf('%d', thriftAngle), ' powerCtrl:', sprintf('%d', powerCtrl)];
title(title_t);
figname = [sprintf('%d度_', thriftAngle), sprintf('%d_dBm', powerCtrl)];
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.fig']);
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.jpg']);

figure(2);
powerCtrl = -106;
x_plot = x(powerOfAreas >= powerCtrl);
y_plot = y(powerOfAreas >= powerCtrl);
plot(x_plot, y_plot, '*');
axis([-80,80,-80,80]);
ylabel('经度方向，正向指向西');
xlabel('纬度方向，正向指向北');
title_t = ['thriftAngle:', sprintf('%d', thriftAngle), ' powerCtrl:', sprintf('%d', powerCtrl)];
title(title_t);
figname = [sprintf('%d度_', thriftAngle), sprintf('%d_dBm', powerCtrl)];
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.fig']);
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.jpg']);

figure(3);
powerCtrl = -105;
x_plot = x(powerOfAreas >= powerCtrl);
y_plot = y(powerOfAreas >= powerCtrl);
plot(x_plot, y_plot, '*');
axis([-80,80,-80,80]);
ylabel('经度方向，正向指向西');
xlabel('纬度方向，正向指向北');
title_t = ['thriftAngle:', sprintf('%d', thriftAngle), ' powerCtrl:', sprintf('%d', powerCtrl)];
title(title_t);
figname = [sprintf('%d度_', thriftAngle), sprintf('%d_dBm', powerCtrl)];
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.fig']);
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.jpg']);

figure(4);
powerCtrl = -103;
x_plot = x(powerOfAreas >= powerCtrl);
y_plot = y(powerOfAreas >= powerCtrl);
plot(x_plot, y_plot, '*');
axis([-80,80,-80,80]);
ylabel('经度方向，正向指向西');
xlabel('纬度方向，正向指向北');
title_t = ['thriftAngle:', sprintf('%d', thriftAngle), ' powerCtrl:', sprintf('%d', powerCtrl)];
title(title_t);
figname = [sprintf('%d度_', thriftAngle), sprintf('%d_dBm', powerCtrl)];
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.fig']);
saveas(gcf, ['C:\Users\houji\Desktop\给李博图\',figname ,'.jpg']);