vector_Sat_normalise = vector_Sat ./ (sqrt(sum(vector_Sat .* vector_Sat, 2)) * ones(1, 3));
vector_SatSpeed_normalise = vector_SatSpeed ./ (sqrt(sum(vector_SatSpeed .* vector_SatSpeed, 2)) * ones(1, 3));
vector_plane_normalise = vector_plane ./ (sqrt(sum(vector_plane .* vector_plane, 2)) * ones(1, 3));
figure(1);
quiver3(0, 0, 0, vector_Sat_normalise(1, 1), vector_Sat_normalise(1, 2), vector_Sat_normalise(1, 3));
text(vector_Sat_normalise(1, 1), vector_Sat_normalise(1, 2), vector_Sat_normalise(1, 3), '指向天空的矢量');
hold on;
quiver3(0, 0, 0, vector_SatSpeed_normalise(1, 1), vector_SatSpeed_normalise(1, 2), vector_SatSpeed_normalise(1, 3));
text(vector_SatSpeed_normalise(1, 1), vector_SatSpeed_normalise(1, 2), vector_SatSpeed_normalise(1, 3), '卫星运动方向的矢量');
hold on;
quiver3(0, 0, 0, vector_plane_normalise(1, 1), vector_plane_normalise(1, 2), vector_plane_normalise(1, 3));
text(vector_plane_normalise(1, 1), vector_plane_normalise(1, 2), vector_plane_normalise(1, 3), '垂直运动方向以及指向地心方向的矢量');
hold on;
quiver3(0, 0, 0, vector_SatAnt(1, 1), vector_SatAnt(1, 2), vector_SatAnt(1, 3));
text( vector_SatAnt(1, 1), vector_SatAnt(1, 2), vector_SatAnt(1, 3), '卫星天线方向');
xlabel('x轴');
ylabel('y轴');
zlabel('z轴');
title('星上坐标系建立示意图');